# ============================================
# Conexão com PostgreSQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/healthdbpostgresql
spring.datasource.username=usuario
spring.datasource.password=9007
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / Hibernate
# ============================================
# ddl-auto: create (cria tabelas), update (atualiza), validate, none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.access-token-validity=900000
jwt.refresh-token-validity=604800000
api.security.token.secret=${JWT_SECRET:miy-key}





server.servlet.context-path=/api/






# ============================================
# Porta do servidor (opcional)
# ============================================
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danielkroda2019@gmail.com
spring.mail.password=slgm ekpr kxkr ydjq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.serialization.write-durations-as-timestamps=false
spring.jackson.serialization.write-dates-as-timestamps=false



