package com.gabrielbl.healthaplication.model;


public enum FatorDeRisco {

    CARGA_DE_TRABALHO,
    RITMO_E_INTENSIDADE,
    CLAREZA_DE_PAPEL,
    AUTONOMIA,
    LIDERANCA,
    RECONHECIMENTO,
    COMUNICACAO,
    JUSTICA_ORGANIZACIONAL,
    RELACOES_INTERPESSOAIS,
    ASSEDIO_MORAL,
    JORNADA_E_PAUSAS,
    TRABALHO_X_VIDA_PESSOAL,
    IMPACTOS_NA_SAUDE_MENTAL;
}
